version: '3.8'

services:
  postgres:
    image: postgres:14.5
    container_name: project_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwerty_386
      POSTGRES_DB: dd_db
    ports:
      - "5432:5432"
    networks:
      - api_network
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  fastapi:
    build:
      context: src/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - api_network
    ports:
      - "8000:8000"

volumes:
  pgdata:

networks:
  api_network:
    external: true
    driver: bridge