services:
  api:
    build:
      context: src/
      dockerfile: Dockerfile
    container_name: project_api
    platform: linux/amd64
    ports:
      - 0.0.0.0:8000:8000
    env_file:
      - .env
    volumes:
      - ./src:/code
    networks:
      - api_network
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:14
    container_name: project_db
    platform: linux/amd64
    env_file:
      - ./.env
    restart: always
    volumes:
      - project_db_data:/var/lib/postgresql/data/
    networks:
      - api_network
    ports:
      - "7015:5432"

volumes:
  project_db_data:

networks:
  api_network:
    external: true
    driver: bridge







environment:
    DATABASE_URL: postgresql://postgres:Qwerty_386@postgres:5432/dd_db